name: background_locator_2
description: A Flutter plugin to request the location even if the app is killed. Sending the location to a dart function in background, also provide a meter filter
version: 2.0.7
homepage: https://github.com/sultan18kh/background_locator_2_gradle_migration
repository: https://github.com/sultan18kh/background_locator_2_gradle_migration
issue_tracker: https://github.com/Yukams/background_locator_2_gradle_migration/issues
platforms:
  android:
  ios:


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: yukams.app.background_locator_2
        pluginClass: BackgroundLocatorPlugin
      ios:
        pluginClass: BackgroundLocatorPlugin
